#!/bin/sh

path=~/wallpapers
path="$(find $path -type d | grep -v .git | wofi --dmenu "Choose category")"

if [ "$folder" == "-h" ] ; then
	echo "First argument must be a folder within ~/wallpapers"
fi

img="$(find $path -type f | grep -v .git | shuf -n 1)"
swww img $img
