#!/bin/sh
status=$(cat /sys/class/power_supply/BAT0/status)
if [ "$status" = "Charging" ]; then
    echo "󱐋"
elif [ "$status" = "Discharging" ]; then
    echo ""
elif [ "$status" = "Not charging" ]; then
    echo ""
fi
