#!/bin/sh

status=$(nmcli g | grep -oE "disconnected")
essid=$(nmcli c | rg '(wifi)|(ethernet)' | awk '{print ($1)}')

if [ $status ] ; then
    icon=""
    text=""
    col="#575268"

else
    icon=""
    text="${essid}"
    col="#a1bdce"
fi



if [ "$1" = "col" ]; then
    echo $col	
elif [ "$1" = "ssid" ]; then
	echo $text
elif [ "$1" = "icon" ]; then
	echo $icon
fi


