#!/bin/sh
connection_type=$(nmcli -t -f TYPE connection show --active >/dev/null)

if echo "$connection_type" rg -q "802-11-wireless">/dev/null; then
    echo "󰈀"
elif echo "$connection_type" rg -q "802-3-ethernet" >/dev/null; then
    echo "󰤨"
else
    echo ""
fi
