#!/bin/sh
# --- OTHER settings ---
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=wayland
export GDK_BACKEND="wayland,x11"


# --- GTK settings ---
gsettings set org.gnome.desktop.interface gtk-theme 'Catppuccin-Mocha-Standard-Blue-Dark'
gsettings set org.gnome.desktop.interface icon-theme 'Flatery-Dark'
gsettings set org.gnome.desktop.interface cursor-theme 'Capitaine Cursors'

# --- gnome polkit ---
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# --- Notification daemon ---
mako &

# --- Background ---
swww init
swww img ~/Pictures/wallpapers/aesthetic/wallhaven-9dmgrk_1920x1080.png

# --- EWW bar ---
eww daemon
eww open bar
eww open bar1

# --- Open apps on startup ---
firefox &


