#!/bin/bash

dots_repo=$HOME/.source/dotfiles
cd $dots_repo
dots=$HOME/.dotfiles
configs=`ls -d */ | grep -Ev 'depends|global'`

save_new_config(){
  print_configs
  echo "Enter name of config"
  echo -n ">> "
  read new_config
  mkdir $dots_repo/$new_config
  cp -r $dots/* $dots_repo/$new_config/
  echo "------------------------------------"
  echo " New config $new_config saved!"
  echo "------------------------------------"
  configs=`ls -d $dots_repo/* | grep -Ev 'depends|global'`
}

save_config(){
  print_configs
  echo "Enter config to replace"
  echo -n ">> "
  read selected_config
  echo "----------------------------------"
  echo "|    !! Ctrl-C to cancel !!      |"
  echo "----------------------------------"
  sleep 3
  echo "[*] Deleting existing dir..."
  rm -rf $dots_repo/$selected_config
  mkdir $dots_repo/$selected_config
  cp -r $dots/* $dots_repo/$selected_config
  echo "------------------------------------"
  echo " config $selected_config replaced! "
  echo "------------------------------------"  
  }

load_config(){
  print_configs
  echo "Enter config to load"
  echo -n ">> "
  read selected_config
  echo "----------------------------------"
  echo "|    !! Ctrl-C to cancel !!      |"
  echo "----------------------------------"
  sleep 3
  echo "[1] Deleting existing dots..."
  rm -rf $dots/*
  echo "[2] Copying new dots..."
  cp -r $dots_repo/$selected_config/* $dots/
  echo "[3] Stowing new configs"
  cd $dots
  stow *
  echo "[*] Config - $selected_config loaded!"
}

load_global_config(){
  echo "Deleting the ~/.dots_global folder in 3 seconds!"
  echo "----------------------------------"
  echo "|    !! Ctrl-C to cancel !!      |"
  echo "----------------------------------"
  sleep 3
  echo "[1] Deleting ~/.dots_global/"
  rm -rf $HOME/.dots_global
  echo "[2] Creating new ~/.dots_global/"
  mkdir $HOME/.dots_global
  echo "[3] Copying global dots to ~/.dots_global/"
  cp -r $dots_repo/global/* $HOME/.dots_global
  echo "[4] Stowing new configs"
  cd $HOME/.dots_global
  stow * --adopt
  echo "[*] Done !"
}

save_global_config(){
  echo "Deleting current global config in 3 seconds!"
  echo "----------------------------------"
  echo "|    !! Ctrl-C to cancel !!      |"
  echo "----------------------------------"
  sleep 3
  echo "[1] Deleting $dots_repo/global/*"
  rm -rf $dots_repo/global/*
  echo "[2] Copying new global configs from ~/.dots_global/"
  cp -r $HOME/.dots_global/* $dots_repo/global/
  echo "[*] Done !"
}

print_configs(){
  echo "-----------------------------------"
  echo "Current configs:"
  echo "${configs[*]}"
  echo "-----------------------------------"
}

main(){
  print_configs
  echo "----------------------------------------------------------"
  echo "| [a] save current config as new                         |"
  echo "| [b] save current config to                             |"
  echo "|   (!! replaces everything in target config!!)          |"
  echo "| [c] switch to config                                   |"
  echo "| [d] load global config                                 |"
  echo "| [e] save global config                                 |"
  echo "----------------------------------------------------------"
  echo -n ">> "
  read choice

  if [ "$choice" == "a" ] ; then
    save_new_config
  elif [ "$choice" == "b" ] ; then
    save_config
  elif [ "$choice" == "c" ] ; then
    load_config
  elif [ "$choice" == "d" ] ; then
    load_global_config
  else
    save_global_config
  fi
}

main