#!/bin/sh
# --- xdg-desktop-portal-hyprland ---
# sleep 1
# killall xdg-desktop-portal-hyprland
# killall xdg-desktop-portal-wlr
# killall xdg-desktop-portal
# /usr/libexec/xdg-desktop-portal-hyprland &
# sleep 2
# /usr/lib/xdg-desktop-portal &

# --- dbus ---
dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus &
dbus-update-activation-environment --all &

# --- OTHER settings ---
# --- Java settings ---
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
export _JAVA_OPTIONS='-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
export JAVA_FONTS=/usr/share/fonts/TTF

# --- GTK settings ---
gsettings set org.gnome.desktop.interface gtk-theme 'Dracula'
gsettings set org.gnome.desktop.interface icon-theme 'Dracula'
gsettings set org.gnome.desktop.interface cursor-theme ''

# --- gnome polkit ---
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# --- Emacs ---
emacs --daemon &

# --- MPD ---
mpd &

# --- Background ---
swww-daemon &

# --- Bar ---
ags &

# --- Foot terminal ---
foot --server &

# --- gammastep ---
gammastep &

# --- open tablet driver ---
# systemctl --user start opentabletdriver

# --- Scripts ---
sleep 5
~/.local/bin/custom/look-away &
