#!/bin/sh
~/.config/hypr/xdg-dp &

# --- OTHER settings ---
export SDL_VIDEODRIVER=wayland
export QT_QPA_PLATFORM=wayland
export GDK_BACKEND="wayland,x11"
# --- Java settings ---
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
# export _JAVA_OPTIONS='-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
export JAVA_FONTS=/usr/share/fonts/TTF

# --- GTK settings ---
gsettings set org.gnome.desktop.interface gtk-theme 'Arc-Dark'
gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
gsettings set org.gnome.desktop.interface cursor-theme 'Capitaine Cursors'

# --- gnome polkit ---
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# --- Pipewire / Audio ---
# /usr/bin/pipewire &
# /usr/bin/pipewire-pulse &
# /usr/bin/wireplumber &

# --- Notification daemon ---
mako &

# --- Emacs ---
emacs --daemon &

# --- MPD ---
mpd

# --- Background ---
swww init &

# --- Bar ---
# ~/.config/eww/launch_bars &

# --- swayidle ---
swayidle -w \
    timeout 300 '~/.local/bin/custom/lockscreen' \
    before-sleep '~/.local/bin/custom/lockscreen' &

# --- Foot terminal ---
foot --server &

waybar &

# --- Open apps on startup ---
# firefox &

# --- Scripts ---
~/.local/bin/custom/look-away &

# --- gammastep ---
# gammastep &
