#!/bin/sh
# --- xdg-desktop-portal-hyprland ---
sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
/usr/libexec/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &

# --- dbus ---
dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus &
