#!/bin/sh
total="$(free --mega | rg Mem: | awk '{print $2}')"
free="$(free --mega | rg Mem: | awk '{print $4}')"
avail="$(free --mega | rg Mem: | awk '{print $7}')"
used=$(expr $total - $avail)
cache="$(free --mega | rg Mem: | awk '{print $6}')"

if [ "$1" = "total" ]; then
    echo $total
elif [ "$1" = "used" ]; then
    echo $used
elif [ "$1" = "free" ]; then
    echo $free
elif [ "$1" = "percent" ]; then
    echo $(awk "BEGIN { pc=100*${used}/${total}; i=int(pc); print (pc-i<0.5)?i:i+1 }")
fi
